Simplify error messages

diff --git a/snapraid-btrfs b/snapraid-btrfs
--- a/snapraid-btrfs
+++ b/snapraid-btrfs
@@ -76,8 +76,7 @@ bash_version_check() {
     if ! { { ((BASH_VERSINFO[0] == 4)) && ((BASH_VERSINFO[1] >= 1)) ; } ||
                ((BASH_VERSINFO[0] > 4)) ; }
     then
-        printf '%s: bash version 4.1 or greater is required' "$my_name" >&2
-        printf ' to use this script\n' >&2
+        printf '%s: bash version 4.1 or greater is required\n' "$my_name" >&2
         exit $EXIT_INTERNAL_ERROR
     fi
 }
@@ -89,8 +88,8 @@ bash_version_check() {
 check_config() {
     # Make sure we found some configs
     if ((${#snapper_configs[@]} == 0)) ; then
-        printf '%s: No snapper configs found for any data ' "$my_name" >&2
-        printf 'drives in snapraid config file\n' >&2
+        printf '%s: No snapper configs found for any data drives in %s\n' \
+               "$my_name" "$config_file" >&2
         exit $EXIT_INVALID_CONFIG
     fi
     # We don't want to snapshot the content files. So, check the directories of
@@ -105,10 +104,9 @@ check_config() {
             content_mount="$(stat --format=%m -- "$content_dir")"
             for i in "${snapper_configs[@]}" ; do
                 if [[ "$content_mount" -ef "${snapper_subvols[$i]}" ]] ; then
-                    printf '%s: Content file %s found in data subvolume %s - ' \
-                           "$my_name" "$field2" "${snapper_subvols[$i]}" >&2
-                    printf 'create a dedicated subvolume for the content ' >&2
-                    printf 'file and try again.\n' >&2
+                    printf '%s: %s found in data subvolume %s - %s\n' \
+                           "$my_name" "$field2" "${snapper_subvols[$i]}" \
+                           'content files must be in separate subvolume' >&2
                     exit $EXIT_INVALID_CONFIG
                 fi
             done
@@ -146,9 +144,8 @@ check_snapraid_arguments() {
     while (($# > 0)) ; do
         case $1 in
             -c|--conf)
-                printf '%s: The -c option may not be passed through - ' \
+                printf '%s: The -c option may not be passed through\n' \
                        "$my_name" >&2
-                printf 'place the -c option before the command instead.\n' >&2
                 invalid_argument_exit ;;
             # snapraid options that take arguments, meaning we should shift 2
             --@(filter?(-disk)|import|plan|older-than|log|start|count)) ;&
@@ -257,9 +254,9 @@ enable_debug_mode() {
 # $2 - Command that caused the ERR condition
 # $3 - Exit status that caused the ERR condition
 err_trap() {
-    printf '%s: %s: %s failed with exit status %s\n' "$my_name" "${1:-?}" \
-           "${2:-unknown command}" "${3:-unknown}" >&2
-    printf 'Stack trace:\n' >&2
+    printf '%s: %s: %s failed with exit status %s\n%s\n' "$my_name" \
+           "${1:-?}" "${2:-unknown command}" "${3:-unknown}" \
+           'Stack trace:' >&2
     local func line script
     local -i frame
     frame=0
@@ -313,7 +310,7 @@ find_configs() {
         fi
     done < <("$my_snapper" list-configs | tail -n +3)
     if ((verbose >= 0)) ; then
-        printf 'Snapper configs found matching snapraid config file:\n'
+        printf 'Snapper configs found:\n'
         for i in "${snapper_configs[@]}" ; do
             printf '%s %s\n' "$i" "${snapper_subvols[$i]}"
         done
@@ -423,18 +420,18 @@ interactive_ask() {
             n|N)
                 exit $EXIT_INTERACTIVE_NO ;;
             *)
-                printf 'Invalid choice! Please enter y or n.\n' >&2 ;;
+                printf 'Invalid choice. Please enter y or n.\n' >&2 ;;
         esac
     done
 }
 
 invalid_argument() {
-    printf '%s: Invalid argument %s!\n' "$my_name" "$1" >&2
+    printf '%s: Invalid argument %s\n' "$my_name" "$1" >&2
     invalid_argument_exit
 }
 
 invalid_argument_exit() {
-    printf 'Use %s -h for help.\n' "$my_name" >&2
+    printf 'Use %s -h for help\n' "$my_name" >&2
     exit $EXIT_INVALID_ARGUMENT
 }
 
@@ -519,7 +516,7 @@ must_be_executable() {
 # call this to make sure $2 is defined when user specifies option requring it
 option_requires_argument() {
     if [[ -z "${2:-}" ]] ; then
-        printf '%s: Option %s requires an argument!\n' "$my_name" "$1" >&2
+        printf '%s: Option %s requires an argument\n' "$my_name" "$1" >&2
         invalid_argument_exit
     fi
 }
@@ -584,8 +581,7 @@ parse_arguments() {
                 invalid_argument "$1" ;;
         esac
     done
-    printf '%s: You must specify a command, or you did not ' "$my_name" >&2
-    printf 'specify an argument to an option that requires one\n' >&2
+    printf '%s: No command specified\n' "$my_name" >&2
     invalid_argument_exit
 }
 
