Split first ~half of main() into new bash_version_check() function

diff --git a/snapraid-btrfs b/snapraid-btrfs
--- a/snapraid-btrfs
+++ b/snapraid-btrfs
@@ -61,6 +61,25 @@ apply_use_snapshot_option() {
     done
 }
 
+bash_version_check() {
+    # bash version 4+ required for associative arrays and
+    # ;& and ;;& terminators in case statements
+    # 4.1+ required for ACL support
+    if ! { [[ "${BASH_VERSINFO[0]}" -gt 4 ]] ||
+               { [[ "${BASH_VERSINFO[0]}" -eq 4 ]] &&
+                     [[ "${BASH_VERSINFO[1]}" -ge 1 ]] ; } ; }
+    then
+        printf '%s: bash version 4.1 or greater is required' "$0" >&2
+        printf ' to use this script\n' >&2
+        exit $EXIT_INTERNAL_ERROR
+    fi
+    # we don't depend on the behavior either way, but lastpipe is faster,
+    # so use it if available (bash version 4.2+)
+    { [[ "${BASH_VERSINFO[0]}" -gt 4 ]] ||
+          [[ "${BASH_VERSINFO[1]}" -ge 2 ]] ; } &&
+        shopt -s lastpipe
+}
+
 # Sanity check snapper configuration
 check_config() {
     # Make sure we found some configs
@@ -368,22 +387,7 @@ invalid_argument() {
 }
 
 main() {
-    # bash version 4+ required for associative arrays and
-    # ;& and ;;& terminators in case statements
-    # 4.1+ required for ACL support
-    if ! { [[ "${BASH_VERSINFO[0]}" -gt 4 ]] ||
-            { [[ "${BASH_VERSINFO[0]}" -eq 4 ]] &&
-                  [[ "${BASH_VERSINFO[1]}" -ge 1 ]] ; } ; }
-    then
-        printf '%s: bash version 4.1 or greater is required' "$0" >&2
-        printf ' to use this script\n' >&2
-        exit $EXIT_INTERNAL_ERROR
-    fi
-    # we don't depend on the behavior either way, but lastpipe is faster,
-    # so use it if available (bash version 4.2+)
-    { [[ "${BASH_VERSINFO[0]}" -gt 4 ]] ||
-          [[ "${BASH_VERSINFO[1]}" -ge 2 ]] ; } &&
-        shopt -s lastpipe
+    bash_version_check
     trap 'err_trap $LINENO $?' ERR
     check_dependencies awk dirname grep sed stat tail tr
     # Set default values for "global" configuration variables
