Add check for invalid snapshot specification

diff --git a/snapraid-btrfs b/snapraid-btrfs
--- a/snapraid-btrfs
+++ b/snapraid-btrfs
@@ -357,11 +357,16 @@ find_snapshots() {
                 use_snapshot[$i]="$("$my_snapper" -c "$i" ls |
                     parse_snapper_ls "$snapper_userdata_key" synced |
                     tail -n 1)" ;;
-            *)
+            +([[:digit:]]))
                 "$my_snapper" -c "$i" ls |
                     parse_snapper_ls |
                     grep -F "${use_snapshot[$i]}" > /dev/null ||
                     use_snapshot[$i]= ;;
+            *)
+                printf '%s: Could not understand snapshot selection %s%s%s\n' \
+                       "$my_name" "${use_snapshot[$i]}" ' for config ' "$i" >&2
+                printf 'Use %s -h for help.\n' "$my_name" >&2
+                exit $EXIT_INVALID_ARGUMENT ;;
         esac
     done
 }
