improve error messages in generate_temp_snapraid_conf()

diff --git a/snapraid-btrfs b/snapraid-btrfs
--- a/snapraid-btrfs
+++ b/snapraid-btrfs
@@ -435,23 +435,24 @@ generate_temp_snapraid_conf() {
         if [[ "${use_snapshot[$i]}" != 0 ]] ; then
             new_path="${snapper_subvols[$i]}/.snapshots/"
             new_path+="${use_snapshot[$i]}/snapshot"
-            if [[ -r "$new_path" ]] && is_btrfs_subvolume "$new_path" ; then
-                # Escape special characters in paths so that they can be
-                # passed to sed as literal strings
-                sed_find="$(sed 's/[].*$^/\[]/\\&/g' \
-                    <<< "${snapper_subvols[$i]}")"
-                sed_replace="$(sed 's/[&/\]/\\&/g' <<< "$new_path")"
-                match_line="$data_line$sed_find"$'[\/]\{0,1\}[\r]\{0,1\}$'
-                sed_exps+=( "/$match_line/s/$sed_find/$sed_replace/" )
-                # also match the deprecated token 'disk' using separate sed
-                # expression to avoid depending on the GNU extension \|
-                match_line="${match_line/data/disk}"
-                sed_exps+=( "/$match_line/s/$sed_find/$sed_replace/" )
-            else
-                printf '%s: Could not read subvolume %s\n' \
-                    "$my_name" "$new_path" >&2
+            if ! is_btrfs_subvolume "$new_path" ; then
+                printf '%s: Invalid snapshot %s\n' "$my_name" "$new_path" >&2
+                exit $EXIT_SNAPSHOT_NOT_FOUND
+            elif ! [[ -r "$new_path" ]] ; then
+                printf '%s: No read permission for %s\n' "$my_name" \
+                    "$new_path" >&2
                 exit $EXIT_NO_PERMISSIONS
             fi
+            # Escape special characters in paths so that they can be
+            # passed to sed as literal strings
+            sed_find="$(sed 's/[].*$^/\[]/\\&/g' <<< "${snapper_subvols[$i]}")"
+            sed_replace="$(sed 's/[&/\]/\\&/g' <<< "$new_path")"
+            match_line="$data_line$sed_find"$'[\/]\{0,1\}[\r]\{0,1\}$'
+            sed_exps+=( "/$match_line/s/$sed_find/$sed_replace/" )
+            # also match the deprecated token 'disk' using separate sed
+            # expression to avoid depending on the GNU extension \|
+            match_line="${match_line/data/disk}"
+            sed_exps+=( "/$match_line/s/$sed_find/$sed_replace/" )
         fi
     done
     if ((${#sed_exps[@]} == 0)) ; then
